spring:
  application:
    name: ai-code-backend
  profiles:
    active: local

  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_code
    username: root
    password: mengxiang
  #redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      ttl: 3600
  session:
    store-type: redis
    timeout: 259200
  mail:
    host: smtp.qq.com
    port: 465
    username: your-qq-email@qq.com
    password: your-qq-smtp-auth-code
    from: your-qq-email@qq.com
    fromName: AI代码生成平台
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
server:
  port: 8124
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 259200
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.easen.aicode.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

# Sa-Token 配置
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: easen-ai-code
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录（为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
